### PR TITLE
Fix RPATH + Use PROJECT_SOURCE_DIR and PROJECT_BINARY_DIR consistently throughout

### PR DESCRIPTION
**Pull request by Chrismarsh**
This fixes the CMakeLists.txt to consistently use `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR` throughout instead of their `SOURCE_*` variants. Indeed, some `PROJECT_*` were already used -- this consistently applies it.

Doing so ensures WindNinja can be built in nested and out-of-source scenarios, such as with [`CPM.cmake`](https://github.com/cpm-cmake/CPM.cmake). 

> In short, there are two predefined variables in CMake: CMAKE_SOURCE_DIR and PROJECT_SOURCE_DIR. CMAKE_SOURCE_DIR refers to the top-level source directory that contains a CMakeLists.txt, while PROJECT_SOURCE_DIR refers to the source directory of the most recent project() command

https://lesleylai.info/en/cmake_src_directory/

This also fixes the RPATH of the `WindNinja_cli` binary on Linux (i.e., when building with shared library) to correctly search for `../lib/` when installed.

### CODE REVIEW

**Comment by nwagenbrenner** [comment]
@Chrismarsh Your changes look good to me. I just merged it. Thanks for submitting the PR.

**Comment by Chrismarsh** [comment]
Thanks @nwagenbrenner. Would it be possible to also get this as a tagged release? Will make it easier for me to reference

**Comment by nwagenbrenner** [comment]
Hi Chris,

Sorry for my slow reply, I've been out of the office. Yes, I'll get you a
tag, probably 3.9.0.2. I'll let you know when it's tagged, but it might be
next week before I can get it done.

Natalie

**Comment by Chrismarsh** [comment]
Thanks, much appreciated.

**Comment by nwagenbrenner** [comment]
Just tagged 3.10.0.0 for you.

**Pull request merged**
