### PR TITLE
Added support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by joserprieto**
Creation of script

./windninja/scripts/build_deps_ubuntu_2204.sh

adapted for Ubuntu 22.04

### CODE REVIEW

**Comment by nwagenbrenner** [comment]
@joserprieto thanks for this PR. We'll review soon.

**Comment by nwagenbrenner** [comment]
@nicknc410 @RuiZhang-kwf8 If you have time, could you also review this PR? Please report back here if you find any issues.

**Comment by masonwillman** [comment]
I have attached two text files (Github does not support .sh attachements) that I was using to look into this script. The first text file has notes with the errors I encountered using a fresh build of Linux. Each error and fix should be documented in the comments. The second script is my attempt at fixing those errors. The second script will run, without error, on a fresh Linux 22.04 build. You can configure, generate, and build Windninja, however, there will be a QT error immediately upon running the project.

The error is: 
mason@testing:~/src/wind/build$ WindNinja
QPixmap: Must construct a QApplication before a QPaintDevice
Aborted (core dumped)
and it occurs at line 72 in file cmake_gui.cpp.  

I will continue to take a look at this and see if I can get my QT to work properly. Because of this, I have not had a chance to test if the newer versions of poppler, proj, and gdal work properly either. 

[build_deps_ubuntu_2204_notes.txt](https://github.com/user-attachments/files/17402056/build_deps_ubuntu_2204_notes.txt)
[build_deps_ubuntu_2204_v2.txt](https://github.com/user-attachments/files/17402057/build_deps_ubuntu_2204_v2.txt)

**Comment by latwood** [comment]
Haven't yet tested a full build with Mason's updated script, but I had gotten to a similar script just reverting back to the old versions of poppler and proj, with the same seg fault errors when running WindNinja gui that Mason described, a cli run of the mass solver running fine. Anyhow, I also found that while openfoam 9 built and installed, WindNinja required changes to the code and to the BC functions to do a cli run of the momentum solver. I've just pushed a WindNinja branch that has these changes for testing.

To test this branch, I would make a fresh clone of windninja somewhere, then in that new branch, "git checkout testFoamUpgrade" to get the updated foam 9 stuff, "git branch" can be handy to see how it changed branches with the checkout. Note that when I finally finish checking the new methods on foam 8 and 2.2.0, that if it turns out these same new changes are useable with foam 8 and 2.2.0, I will likely delete that branch and start making a new one. But for just looking at and quickly testing the code, the branch should be good enough for now.

Then, in your ~/.bashrc file, I would comment out the line that you added "export WINDNINJA_DATA=~/src/wind/windninja/data", and add a new line with "export WINDNINJA_DATA=" to the path of the testFoamUpgrade branch. Note you can select versions of openfoam via commenting out the "source /opt/openfoam8/etc/bashrc" or "source /opt/openfoam9/etc/bashrc", swapping to the uncommented form for whatever version of openfoam you have installed and are trying out. Then do "source ~/.bashrc" to update the environment with the changes.

Then, might need to revise this if you want to keep the old foam BCs around, need to "cd $FOAM_RUN/../applications/.." and "rm -rf applications platforms", then "mkdir applications", "cd applications", then copy over the newly updated BCs, "cp -r ~/src/wind/windninja/src/ninjafoam/9/* $FOAM_RUN/../applications". Then the remainder of the normal BC building commands "cd $FOAM_RUN/../applications", "wmake libso", "cd utility/applyInit", "wmake". Note that the building windninja on linux page should be updated to be "~/src/wind/windninja/src/ninjafoam/8/*", not "~/src/wind/windninja/src/ninjafoam/*" as it currently stands. Note that when just editing the files without doing a full fresh copy, wclean for each wmake location and then deleting the platforms directory (libs and bin files don't delete with wclean) is what I usually do if I need a hard reset.

Sounds like we are good to go now, other than figuring out how to get WindNinja gui to work with qt4. Strangely, we were able to get a simple example script with basic qt4 stuff, including the line of code that breaks in WindNinja, to compile and run without problems, but it doesn't seem like an easy thing to figure out.

**Comment by masonwillman** [comment]
Using the instructions @latwood gave for openFoam9, the command line is fully functional in Ubuntu 22.04 with the new script. Currently, we are still facing issues identifying what is causing the QT4 error. We have isolated it to the WindNinja project itself and not QT, so we need to look at the project files themselves to fix the error. @latwood made progress by removing files using QT in the CMakeLists.txt. By slowly adding the files back, we may be able to find the culprit files. That seems to be the next logical step to getting the build working.

**Comment by joserprieto** [comment]
Hi, @masonwillman; i made minimal changes on the script; but, if you want, i can make it more modular and adjustable; wrapping and isolating "sections" or "parts" in functions; using "modern" commands like "apt" and not "apt-get"; and so on.

Tell me if you are interested, and i will work on it a little ;) .

Regards.

PS: What about Ubuntu 24.04? Anyone made any test of Windninja in Ubuntu 24.04?
PS2: And.. What about Debian? I like more Debian than Ubuntu, because... A lot of things; anyone tested Windninja in Debian 11 or 12?

**Comment by masonwillman** [comment]
Hi @joserprieto! If you have any additions or modifications that would improve the script, then I am absolutely interested in seeing what come up with. My latest version of the script as been committed, and if you have any questions about the changes I made, let me know. Most of them had to do with needed extra libraries or changing to cmake build commands. 

I'll answer your questions in two parts:
1. We have not tested WindNinja on Ubuntu 24.04. WindNinja has some very old dependencies (QT4 being the biggest example) that make it difficult for us to development on newer Ubuntu versions. We are currently collaborating to rewrite the GUI code, which will remove those issues. If you continue to work on the script, I would recommend focusing on Ubuntu 22.04 to reduce the amount of issues that you may face. 
2. From my understanding, Ubuntu is based on Debian, so it might not be difficult to find the correlating Debian version and see about building WindNinja on it. However, we have not tested it. We primarily work in Ubuntu for development, which is why we focus on it over other Linux distributions like Redhat or Debian. 

If you have any other questions, please do not hesitate to ask. We always love to see people helping contribute to the project!

**Comment by latwood** [comment]
Went to merge this pull request with the `qt4guiForUbuntu22o04` branch, but ran into problems. I got close to resolving them by doing `git pull https://github.com/joserprieto/windninja.git master --rebase`, but that method caused other problems. The goal I think, is to try to force these pull request commits of the `build_deps_ubuntu_2204.sh` script to be appended to AFTER whatever changes/commits to `build_deps_ubuntu_2204.sh` were done in the `qt4guiForUbuntu22o04` branch, replacing the `build_deps_ubuntu_2204.sh` of the `qt4guiForUbuntu22o04` branch with the pull request form.

Anyhow, will come back to this next week.

**Comment by joserprieto** [comment]
> Hi @joserprieto! If you have any additions or modifications that would improve the script, then I am absolutely interested in seeing what come up with. My latest version of the script as been committed, and if you have any questions about the changes I made, let me know. Most of them had to do with needing extra libraries or changing to cmake build commands.
> 
> I'll answer your questions in two parts:
> 
> 1. We have not tested WindNinja on Ubuntu 24.04. WindNinja has some very old dependencies (QT4 being the biggest example) that make it difficult for us to development on newer Ubuntu versions. We are currently collaborating to rewrite the GUI code, which will remove those issues. If you continue to work on the script, I would recommend focusing on Ubuntu 22.04 to reduce the amount of issues that you may face.
> 2. From my understanding, Ubuntu is based on Debian, so it might not be difficult to find the correlating Debian version and see about building WindNinja on it. However, we have not tested it. We primarily work in Ubuntu for development, which is why we focus on it over other Linux distributions like Redhat or Debian.
> 
> If you have any other questions, please do not hesitate to ask. We always love to see people helping contribute to the project!

Hi again!

So, with your comments, I think that the biggest problem or "trouble" for get a functional version working on Ubuntu 24.04 and Debian 12, it's QT 4, isn't it?


If we review the script code:

```bash
#!/bin/bash

PREFIX=/usr/local
POPPLER="poppler-0.23.4"
PROJ="proj-6.3.2"
GDAL="gdal-3.2.1"

#Dependencies
sudo -E apt-get install -y pkg-config libfontconfig1-dev libcurl4-gnutls-dev libnetcdf-dev \
                           libboost-program-options-dev libboost-date-time-dev libgeos-dev \
                           libboost-test-dev libsqlite3-dev sqlite3

#Get and build poppler for PDF support in GDAL
wget https://poppler.freedesktop.org/$POPPLER.tar.xz
tar -xvf $POPPLER.tar.xz 
cd $POPPLER/
./configure --prefix=$PREFIX --enable-xpdf-headers
make
sudo make install
cd ..

#Get and build proj
wget https://download.osgeo.org/proj/$PROJ.tar.gz
tar xvfz $PROJ.tar.gz
cd $PROJ
./configure --prefix=$PREFIX
make clean
make
sudo make install
cd ..

#Get and build GDAL with poppler support
wget https://download.osgeo.org/gdal/${GDAL:5}/$GDAL.tar.gz
tar -xvf $GDAL.tar.gz 
cd $GDAL/
./configure --prefix=$PREFIX --with-poppler=$PREFIX
make -j 8
sudo make install
cd ..

#Add qt4 libs from ppa
#See here for more info:
#https://ubuntuhandbook.org/index.php/2020/07/install-qt4-ubuntu-20-04/
sudo add-apt-repository ppa:rock-core/qt4
sudo apt-get update
sudo -E apt-get install -y libqt4-dev libqtwebkit-dev 

#Use OpenFOAM 8
#add the dl.openfoam.org repo and install OpenFOAM 8
sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
sudo add-apt-repository http://dl.openfoam.org/ubuntu
sudo apt-get update
sudo -E apt-get install -y openfoam8
echo "source /opt/openfoam8/etc/bashrc" >> ~/.bashrc
```

I think that dependencies will be (on Ubuntu 20.04):

- Official repositories:
  - pkg-config
  - libfontconfig1-dev
  - libcurl4-gnutls-dev
  - libnetcdf-dev
  - libboost-program-options-dev
  - libboost-date-time-dev
  - libgeos-dev
  - libboost-test-dev
  - libsqlite3-dev
  - sqlite3
- ppa:rock-core/qt4 repositroy
  - libqt4-dev
  - libqtwebkit-dev

And, of course (but, compiling):

- GDAL
- POPPLER
- PROJ
- OpenFOAM (seems to work with version 9, isn't?)

So, if we do a table similar to this:

|                              | Ubuntu 20.04                 | Ubuntu 22.02 | Ubuntu 24.04 | Debian 11 | Debian 12 |
| ---------------------------- | ---------------------------- | ------------ | ------------ | --------- | --------- |
| Official repositories        | pkg-config                   |              |              |           |           |
|                              | libfontconfig1-dev           |              |              |           |           |
|                              | libcurl4-gnutls-dev          |              |              |           |           |
|                              | libnetcdf-dev                |              |              |           |           |
|                              | libboost-program-options-dev |              |              |           |           |
|                              | libboost-date-time-dev       |              |              |           |           |
|                              | libgeos-dev                  |              |              |           |           |
|                              | libboost-test-dev            |              |              |           |           |
|                              | libsqlite3-dev               |              |              |           |           |
|                              | sqlite3                      |              |              |           |           |
| ppa:rock-core/qt4 repositroy |                              |              |              |           |           |
|                              | libqt4-dev                   |              |              |           |           |
|                              | libqtwebkit-dev              |              |              |           |           |
| source && compile            |                              |              |              |           |           |
|                              | GDAL                         |              |              |           |           |
|                              | POPPLER                      |              |              |           |           |
|                              | PROJ                         |              |              |           |           |
|                              | OpenFOAM 8                   |              |              |           |           |

So, if we fill all the empty cells, we can have all the needed dependencies for every system.

Please, review this table, and add every dependency that you think that is needed; and i promise that in my next holidays (on 1st december), i will get all the info and work on it :)

**Comment by joserprieto** [comment]
Note: i'm very interested on this subject, because in the project that i work:

https://einforex.net/es/176-2/

EInforex Fleet / EInforex Ignis

We use algorithms to get data from our UAV, or our aerial vehicles (helicopters and so on), on our fire extinction missions, and with this data, we try to get new (predictive) data, like previsions of fire advance, and so on.

Right now, we execute the algorithms (all of them based on R or Python), in a isolate machine; but i want to migrate all of this to containers (some of them already are running in containers); so, if we can have a working version on a Debian 12 instance, "it's easy" to migrate it to a container image :)

(And i will be more happy!)

Regards.

**Comment by masonwillman** [comment]
@joserprieto I think the main problem is not so much a dependency list but dependency support. Qt 4 has been out of support for a long time and trying to get our existing code to function properly on Ubuntu 22.04 without a container is proving a challenge. If we were to migrate to an even newer version of Ubuntu, I fear that would require updating our Qt version (which we are currently working towards). In regards to WindNinja's use cases at your place of work, we do have a dockerfile located in the repo. I would recommend using that to containerize WindNinja for your needs. The file path is simply windninja/Dockerfile.

**Pull request merged**
